---
- name: Check if node already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join worker to cluster
  command: "{{ hostvars[groups['k8s-master'][0]]['join_command'] }} --ignore-preflight-errors=NumCPU,Hostname"
  when: not kubelet_conf.stat.exists
