---
- name: Install K8s prerequisites on all nodes
  hosts: k8s
  become: yes
  roles:
    - k8s-prereqs

- name: Initialize K8s master
  hosts: k8s-master
  become: yes
  roles:
    - kubeadm-init

- name: Join workers to cluster
  hosts: k8s-workers
  become: yes
  roles:
    - kubeadm-join
